// Read the freshly-built wasm artifact and emit it as a base64 string in
// `src/wasm_inline.ts`, so the bundled JS module is fully self-contained.
//
// Run via `bun run scripts/embed-wasm.ts` (or `bun run build:embed`).

import { resolve } from "node:path";

const here = import.meta.dir;
const WASM_PATH = resolve(here, "../../../core/zig-out/wasm/luv_core.wasm");
const OUT_PATH = resolve(here, "../src/wasm_inline.ts");

const bytes = await Bun.file(WASM_PATH).bytes();
const base64 = Buffer.from(bytes).toString("base64");

const content = `// AUTO-GENERATED by scripts/embed-wasm.ts. Do not edit.
// Source: core/zig-out/wasm/luv_core.wasm (${bytes.length} bytes)
export const wasmBase64 = ${JSON.stringify(base64)};
`;

await Bun.write(OUT_PATH, content);
console.log(
  `embedded ${bytes.length} wasm bytes → ${base64.length} base64 chars → ${OUT_PATH}`,
);
