// Generates src/wasm/embedded.generated.ts — the wasm bytes base64-embedded
// so the bundle has no fetch/asset dependency (codec-boundary + bundler
// matrix friendliness). Run via `bun run build:embed` after `zig build wasm`.
// The generated file is committed so the JS build never needs Zig.

const WASM = new URL(
  "../../../core/zig-out/wasm/luv_core.wasm",
  import.meta.url,
);
const OUT = new URL("../src/wasm/embedded.generated.ts", import.meta.url);

const bytes = new Uint8Array(await Bun.file(WASM).arrayBuffer());
const b64 = Buffer.from(bytes).toString("base64");

const ts = `// @generated by scripts/embed-wasm.ts from core/zig-out/wasm/luv_core.wasm
// DO NOT EDIT. Re-run \`bun run build:embed\` after \`zig build wasm\`.
//
// Base64-embedded so the bundle carries the wasm with no fetch/asset step
// (works identically in browser/Node/Bun and every bundler).
/* eslint-disable */
const B64 =
  "${b64}";

// No explicit annotation: infers Uint8Array<ArrayBuffer> (a valid
// BufferSource); annotating as plain Uint8Array widens to ArrayBufferLike.
export const wasmBytes = Uint8Array.from(atob(B64), (c) => c.charCodeAt(0));
`;

await Bun.write(OUT, ts);
console.log(`embed-wasm: wrote ${bytes.length} bytes -> embedded.generated.ts (${b64.length} b64 chars)`);
