//! Zig -> per-language SDK loader generator (plans/generate-sdks.md, P2).
//!
//! Reads the declarative boundary descriptor `wasm_abi/abi.zig` and emits the
//! mechanical wasm loader: the typed export interface + the fixed marshalling
//! seam (instance bootstrap, `invoke`, `callWasm`, and the decoder/agent
//! handle helpers). 100% derived from `abi.bricks` — a new wasm export added
//! to the descriptor flows into the loader with no hand-editing.
//!
//! NOT emitted here: per-brick wire codecs + semantic glue (the `*_bridge.ts`
//! success transforms / error reconstruction). Those carry per-brick wire
//! layout and belong to the declarative-wire-schema phase (P3); generating
//! them now would just relocate hand-written code into the generator.
//!
//! Backend is TypeScript only for now; the per-language-differing emitter is
//! the single seam a second language (P4) plugs into.
//!
//! Usage: gen_sdk <output-path>   (build runs it with cwd = core/)

const std = @import("std");
const Io = std.Io;
const abi = @import("abi");

fn has(comptime kind: abi.AbiKind) bool {
    comptime {
        for (abi.bricks) |b| if (b.abi == kind) return true;
        return false;
    }
}

/// First brick of a kind — the handle families (decoder/agent) are singletons
/// in the descriptor; we read their export names off the matching brick so a
/// rename in abi.zig regenerates correctly.
fn brickOf(comptime kind: abi.AbiKind) abi.Brick {
    comptime {
        for (abi.bricks) |b| if (b.abi == kind) return b;
        @compileError("no brick of requested kind");
    }
}

const HEADER =
    \\// @generated by core/tools/gen_sdk.zig from core/src/wasm_abi/abi.zig
    \\// — DO NOT EDIT BY HAND. Re-run `make gen` after changing the descriptor.
    \\//
    \\// The mechanical wasm loader: typed exports + the fixed marshalling seam.
    \\// Per-brick codec/semantics live in the (still hand-written) *_bridge.ts.
    \\
    \\import { wasmBytes } from "./embedded.generated.ts";
    \\
    \\interface SyncExports {
    \\  memory: WebAssembly.Memory;
    \\  luv_alloc(len: number): number;
    \\  luv_free(ptr: number, len: number): void;
    \\
;

const EXPORTS_TAIL =
    \\  // Generic lookup for the per-brick (i,l,a,b)->i32 exports.
    \\  [name: string]: unknown;
    \\}
    \\
    \\// Synchronous instantiation at module load (no top-level await). Safari/
    \\// Firefox/Node/Bun have no size cap; Chrome raised its main-thread limit
    \\// to 8 MB in Chrome 115 (our wasm ~116 KB) — effective floor Chrome 115.
    \\const instance = new WebAssembly.Instance(
    \\  new WebAssembly.Module(wasmBytes),
    \\  {},
    \\);
    \\const ex = instance.exports as unknown as SyncExports;
    \\
    \\const u8 = (): Uint8Array => new Uint8Array(ex.memory.buffer);
    \\const dv = (): DataView => new DataView(ex.memory.buffer);
    \\
    \\function invoke(
    \\  fn: (i: number, l: number, a: number, b: number) => number,
    \\  input: Uint8Array,
    \\  what: string,
    \\): Uint8Array {
    \\  let inPtr = 0;
    \\  if (input.length > 0) {
    \\    inPtr = ex.luv_alloc(input.length);
    \\    if (inPtr === 0) throw new Error("luv_alloc failed");
    \\    u8().set(input, inPtr);
    \\  }
    \\  const cell = ex.luv_alloc(8);
    \\  try {
    \\    const status = fn(inPtr, input.length, cell, cell + 4);
    \\    if (status !== 0) throw new Error(`${what} failed: status ${status}`);
    \\    const outPtr = dv().getUint32(cell, true);
    \\    const outLen = dv().getUint32(cell + 4, true);
    \\    const out = u8().slice(outPtr, outPtr + outLen);
    \\    ex.luv_free(outPtr, outLen);
    \\    return out;
    \\  } finally {
    \\    if (input.length > 0) ex.luv_free(inPtr, input.length);
    \\    ex.luv_free(cell, 8);
    \\  }
    \\}
    \\
    \\/** Generic synchronous call to an (in,in_len,out_ptr,out_len)->i32 export.
    \\ *  The shared low-level seam every per-brick bridge uses — bricks own
    \\ *  their codec, not this file. */
    \\export function callWasm(exportName: string, input: Uint8Array): Uint8Array {
    \\  const fn = ex[exportName] as
    \\    | ((i: number, l: number, a: number, b: number) => number)
    \\    | undefined;
    \\  if (typeof fn !== "function") {
    \\    throw new Error(`wasm export not found: ${exportName}`);
    \\  }
    \\  return invoke((i, l, a, b) => fn(i, l, a, b), input, exportName);
    \\}
    \\
;

// Decoder handle family — body is fixed; export names come from the descriptor.
fn decoderBlock() []const u8 {
    comptime {
        const d = brickOf(.decoder);
        const new_ex = d.wasm_export; // luv_decoder_new
        const feed_ex = d.aux_exports[0]; // luv_decoder_feed
        const free_ex = d.aux_exports[1]; // luv_decoder_free
        return "\n// Streaming SSE decoder — stateful handle (sse_decoder brick).\n" ++
            "export function decoderNew(): number {\n" ++
            "  const h = ex." ++ new_ex ++ "();\n" ++
            "  if (h === 0) throw new Error(\"" ++ new_ex ++ " failed\");\n" ++
            "  return h;\n}\n\n" ++
            "export function decoderFree(handle: number): void {\n" ++
            "  ex." ++ free_ex ++ "(handle);\n}\n\n" ++
            "export function decoderFeed(handle: number, chunk: Uint8Array): Uint8Array {\n" ++
            "  let inPtr = 0;\n" ++
            "  if (chunk.length > 0) {\n" ++
            "    inPtr = ex.luv_alloc(chunk.length);\n" ++
            "    if (inPtr === 0) throw new Error(\"luv_alloc failed\");\n" ++
            "    u8().set(chunk, inPtr);\n  }\n" ++
            "  const cell = ex.luv_alloc(8);\n  try {\n" ++
            "    const st = ex." ++ feed_ex ++ "(handle, inPtr, chunk.length, cell, cell + 4);\n" ++
            "    if (st !== 0) throw new Error(`" ++ feed_ex ++ " failed: status ${st}`);\n" ++
            "    const op = dv().getUint32(cell, true);\n" ++
            "    const ol = dv().getUint32(cell + 4, true);\n" ++
            "    const out = u8().slice(op, op + ol);\n" ++
            "    ex.luv_free(op, ol);\n    return out;\n" ++
            "  } finally {\n" ++
            "    if (chunk.length > 0) ex.luv_free(inPtr, chunk.length);\n" ++
            "    ex.luv_free(cell, 8);\n  }\n}\n";
    }
}

// Agent machine family — body is fixed; export names come from the descriptor.
fn agentBlock() []const u8 {
    comptime {
        const g = brickOf(.agent);
        const start = g.wasm_export; // agent_start
        const poll = g.aux_exports[0]; // agent_poll
        const feed_reply = g.aux_exports[1]; // agent_feed_reply
        const feed_tools = g.aux_exports[2]; // agent_feed_tools
        const abort = g.aux_exports[3]; // agent_abort
        const destroy = g.aux_exports[4]; // agent_destroy
        return "\n// Sans-IO agent loop — handle-based (the agent host driver).\n" ++
            "export function agentStart(input: Uint8Array): number {\n" ++
            "  let inPtr = 0;\n" ++
            "  if (input.length > 0) {\n" ++
            "    inPtr = ex.luv_alloc(input.length);\n" ++
            "    if (inPtr === 0) throw new Error(\"luv_alloc failed\");\n" ++
            "    u8().set(input, inPtr);\n  }\n  try {\n" ++
            "    const h = ex." ++ start ++ "(inPtr, input.length);\n" ++
            "    if (h === 0) throw new Error(\"" ++ start ++ " failed\");\n" ++
            "    return h;\n  } finally {\n" ++
            "    if (input.length > 0) ex.luv_free(inPtr, input.length);\n  }\n}\n\n" ++
            "/** poll -> the tag+payload frame (caller parses tag byte 0). */\n" ++
            "export function agentPoll(handle: number): Uint8Array {\n" ++
            "  const cell = ex.luv_alloc(8);\n  try {\n" ++
            "    const st = ex." ++ poll ++ "(handle, cell, cell + 4);\n" ++
            "    if (st !== 0) throw new Error(`" ++ poll ++ " failed: status ${st}`);\n" ++
            "    const op = dv().getUint32(cell, true);\n" ++
            "    const ol = dv().getUint32(cell + 4, true);\n" ++
            "    const out = u8().slice(op, op + ol);\n" ++
            "    ex.luv_free(op, ol);\n    return out;\n" ++
            "  } finally {\n    ex.luv_free(cell, 8);\n  }\n}\n\n" ++
            "function agentFeed(\n" ++
            "  fn: (h: number, i: number, l: number) => number,\n" ++
            "  handle: number,\n  bytes: Uint8Array,\n  what: string,\n): void {\n" ++
            "  let p = 0;\n" ++
            "  if (bytes.length > 0) {\n" ++
            "    p = ex.luv_alloc(bytes.length);\n" ++
            "    if (p === 0) throw new Error(\"luv_alloc failed\");\n" ++
            "    u8().set(bytes, p);\n  }\n  try {\n" ++
            "    const st = fn(handle, p, bytes.length);\n" ++
            "    if (st !== 0) throw new Error(`${what} failed: status ${st}`);\n" ++
            "  } finally {\n" ++
            "    if (bytes.length > 0) ex.luv_free(p, bytes.length);\n  }\n}\n\n" ++
            "export function agentFeedReply(handle: number, bytes: Uint8Array): void {\n" ++
            "  agentFeed((h, i, l) => ex." ++ feed_reply ++ "(h, i, l), handle, bytes, \"" ++ feed_reply ++ "\");\n}\n" ++
            "export function agentFeedTools(handle: number, bytes: Uint8Array): void {\n" ++
            "  agentFeed((h, i, l) => ex." ++ feed_tools ++ "(h, i, l), handle, bytes, \"" ++ feed_tools ++ "\");\n}\n" ++
            "export function agentAbort(handle: number): void {\n" ++
            "  ex." ++ abort ++ "(handle);\n}\n" ++
            "export function agentDestroy(handle: number): void {\n" ++
            "  ex." ++ destroy ++ "(handle);\n}\n";
    }
}

const GENERATED = blk: {
    var out: []const u8 = HEADER;

    // Typed bytes_io exports (the per-brick (i,l,a,b)->i32 surface).
    for (abi.bricks) |b| {
        if (b.abi == .bytes_io) {
            out = out ++ "  " ++ b.wasm_export ++
                "(i: number, l: number, a: number, b: number): number;\n";
        }
    }
    // Decoder family signatures.
    if (has(.decoder)) {
        const d = brickOf(.decoder);
        out = out ++ "  " ++ d.wasm_export ++ "(): number;\n" ++
            "  " ++ d.aux_exports[1] ++ "(handle: number): void;\n" ++
            "  " ++ d.aux_exports[0] ++
            "(h: number, i: number, l: number, a: number, b: number): number;\n";
    }
    // Agent family signatures.
    if (has(.agent)) {
        const g = brickOf(.agent);
        out = out ++ "  " ++ g.wasm_export ++ "(i: number, l: number): number;\n" ++
            "  " ++ g.aux_exports[0] ++ "(h: number, a: number, b: number): number;\n" ++
            "  " ++ g.aux_exports[1] ++ "(h: number, i: number, l: number): number;\n" ++
            "  " ++ g.aux_exports[2] ++ "(h: number, i: number, l: number): number;\n" ++
            "  " ++ g.aux_exports[3] ++ "(h: number): void;\n" ++
            "  " ++ g.aux_exports[4] ++ "(h: number): void;\n";
    }

    out = out ++ EXPORTS_TAIL;
    if (has(.decoder)) out = out ++ decoderBlock();
    if (has(.agent)) out = out ++ agentBlock();
    break :blk out;
};

// Build runs this with cwd = core/, so the path is repo-relative from there.
const OUT_PATH = "../lib/js/src/wasm/loader.generated.ts";

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const cwd = Io.Dir.cwd();
    try cwd.writeFile(io, .{ .sub_path = OUT_PATH, .data = GENERATED });
}
