//! P3 spike — TS wire-codec generator (plans/generate-sdks.md).
//!
//! Walks the SAME `wire.tool_args_in` schema the Zig encoder consumes and
//! emits the TS framing encoder. One schema -> two codecs. Proves the
//! declarative wire schema can drive the per-language codec; the full P3
//! rollout extends the field-kind set + emits decoders + every message.
//!
//! Usage: gen_wire   (build runs it with cwd = core/)

const std = @import("std");
const Io = std.Io;
const wire = @import("wire");

/// Emit the TS framing encoder for a message by walking its fields. The
/// value-encoding (JSON.stringify + TextEncoder) stays in the brick bridge;
/// this owns only the byte framing — exactly the hand layout it replaces.
fn emitEncoder(comptime m: wire.Message) []const u8 {
    comptime {
        // Params: lp_bytes -> required Uint8Array; opt_lp_bytes -> optional.
        var params: []const u8 = "";
        var size: []const u8 = "0";
        var body: []const u8 = "";
        var first = true;
        for (m.fields) |f| {
            switch (f.kind) {
                .lp_bytes => {
                    params = params ++ (if (first) "" else ", ") ++ f.name ++ ": Uint8Array";
                    first = false;
                    size = size ++ " + 4 + " ++ f.name ++ ".length";
                    body = body ++
                        "  dv.setUint32(pos, " ++ f.name ++ ".length, true); pos += 4;\n" ++
                        "  buf.set(" ++ f.name ++ ", pos); pos += " ++ f.name ++ ".length;\n";
                },
                .u8_flag => {
                    // Driven by the following opt field's presence.
                    size = size ++ " + 1";
                    body = body ++ "  buf[pos] = has ? 1 : 0; pos += 1;\n";
                },
                .opt_lp_bytes => {
                    params = params ++ (if (first) "" else ", ") ++ f.name ++ ": Uint8Array | undefined";
                    first = false;
                    size = size ++ " + (has ? 4 + " ++ f.name ++ "!.length : 0)";
                    body = body ++
                        "  if (has) {\n" ++
                        "    dv.setUint32(pos, " ++ f.name ++ "!.length, true); pos += 4;\n" ++
                        "    buf.set(" ++ f.name ++ "!, pos); pos += " ++ f.name ++ "!.length;\n" ++
                        "  }\n";
                },
            }
        }
        // The spike schema has exactly one optional, named `schema`; `has`
        // is its presence. (P3 rollout: derive the flag<->opt binding by
        // name pairing in the schema rather than this single convention.)
        return "export function encode" ++ m.name ++ "(" ++ params ++ "): Uint8Array {\n" ++
            "  const has = schema !== undefined;\n" ++
            "  const total = " ++ size ++ ";\n" ++
            "  const buf = new Uint8Array(total);\n" ++
            "  const dv = new DataView(buf.buffer);\n" ++
            "  let pos = 0;\n" ++
            body ++
            "  return buf;\n}\n";
    }
}

const GENERATED = blk: {
    break :blk "// @generated by core/tools/gen_wire.zig from " ++
        "core/src/wasm_abi/wire.zig — DO NOT EDIT BY HAND.\n" ++
        "// One declarative schema drives this TS framing codec AND the\n" ++
        "// schema-driven Zig encoder. Re-run `make gen` after editing wire.zig.\n\n" ++
        emitEncoder(wire.tool_args_in);
};

// Build runs this with cwd = core/, so the path is repo-relative from there.
const OUT_PATH = "../lib/js/src/wasm/wire.generated.ts";

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const cwd = Io.Dir.cwd();
    try cwd.writeFile(io, .{ .sub_path = OUT_PATH, .data = GENERATED });
}
