//! Zig -> TS type generator (Stream B).
//!
//! Comptime-reflects the canonical types in morphisms/luv/luv.zig and emits
//! TypeScript. snake_case -> camelCase; []const u8 -> string; ints/floats ->
//! number; bool -> boolean; ?T -> optional property; []const T -> T[];
//! std.json.Value -> unknown; enum -> string-literal union; tagged union ->
//! discriminated union.
//!
//! Output is the single source of truth for the pure-data type shapes. Only
//! the structurally-identical subset (Role/StopReason/Usage) is re-wired into
//! types.ts (B2); the rest are emitted as the canonical reference projection.
//!
//! Usage: gen_ts_types <output-path>

const std = @import("std");
const Io = std.Io;
const luv = @import("luv");

fn lastSeg(comptime name: []const u8) []const u8 {
    comptime {
        var i = name.len;
        while (i > 0) : (i -= 1) {
            if (name[i - 1] == '.') return name[i..];
        }
        return name;
    }
}

fn camel(comptime s: []const u8) []const u8 {
    comptime {
        var out: []const u8 = "";
        var up = false;
        for (s) |c| {
            if (c == '_') {
                up = true;
            } else if (up) {
                out = out ++ [_]u8{std.ascii.toUpper(c)};
                up = false;
            } else {
                out = out ++ [_]u8{c};
            }
        }
        return out;
    }
}

fn tsType(comptime T: type) []const u8 {
    comptime {
        if (T == std.json.Value) return "unknown";
        return switch (@typeInfo(T)) {
            .bool => "boolean",
            .int, .float, .comptime_int, .comptime_float => "number",
            .optional => |o| tsType(o.child),
            .pointer => |p| if (p.size == .slice)
                (if (p.child == u8) "string" else tsType(p.child) ++ "[]")
            else
                @compileError("unsupported pointer"),
            .@"struct", .@"enum", .@"union" => lastSeg(@typeName(T)),
            else => @compileError("unsupported type: " ++ @typeName(T)),
        };
    }
}

fn isOptional(comptime T: type) bool {
    return @typeInfo(T) == .optional;
}

fn emitDecl(comptime name: []const u8, comptime T: type) []const u8 {
    comptime {
        return switch (@typeInfo(T)) {
            .@"enum" => |e| blk: {
                var u: []const u8 = "";
                for (e.fields, 0..) |f, i| {
                    u = u ++ (if (i == 0) "" else " | ") ++ "\"" ++ f.name ++ "\"";
                }
                break :blk "export type " ++ name ++ " = " ++ u ++ ";\n";
            },
            .@"struct" => |s| blk: {
                var body: []const u8 = "";
                for (s.fields) |f| {
                    const opt = isOptional(f.type);
                    body = body ++ "  readonly " ++ camel(f.name) ++
                        (if (opt) "?: " else ": ") ++ tsType(f.type) ++ ";\n";
                }
                break :blk "export interface " ++ name ++ " {\n" ++ body ++ "}\n";
            },
            .@"union" => |un| blk: {
                var u: []const u8 = "";
                for (un.fields, 0..) |f, i| {
                    u = u ++ (if (i == 0) "" else " | ") ++
                        "{ readonly " ++ camel(f.name) ++ ": " ++ tsType(f.type) ++ " }";
                }
                break :blk "export type " ++ name ++ " = " ++ u ++ ";\n";
            },
            .pointer => "export type " ++ name ++ " = " ++ tsType(T) ++ ";\n",
            else => @compileError("cannot emit decl for " ++ name),
        };
    }
}

// Ordered list of canonical types to project.
const TYPES = .{
    .{ "Role", luv.Role },
    .{ "StopReason", luv.StopReason },
    .{ "ToolResult", luv.ToolResult },
    .{ "ToolCall", luv.ToolCall },
    .{ "Tool", luv.Tool },
    .{ "Message", luv.Message },
    .{ "Conversation", luv.Conversation },
    .{ "Usage", luv.Usage },
    .{ "Reply", luv.Reply },
};

const GENERATED = blk: {
    var out: []const u8 =
        \\// @generated by core/tools/gen_ts_types.zig from
        \\// core/src/morphisms/luv/luv.zig — DO NOT EDIT BY HAND.
        \\//
        \\// Source of truth for the canonical pure-data type shapes. Re-run
        \\// `make gen-ts` after changing luv.zig. types.ts re-exports the
        \\// structurally-identical subset (Role, StopReason, Usage); the rest
        \\// are the canonical reference projection.
        \\
        \\
    ;
    for (TYPES) |entry| {
        out = out ++ emitDecl(entry[0], entry[1]) ++ "\n";
    }
    break :blk out;
};

// Build runs this with cwd = core/, so the path is repo-relative from there.
const OUT_PATH = "../lib/js/src/types.generated.ts";

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const cwd = Io.Dir.cwd();
    try cwd.writeFile(io, .{ .sub_path = OUT_PATH, .data = GENERATED });
}
