// @generated by core/tools/gen_sdk.zig from core/src/wasm_abi/abi.zig
// — DO NOT EDIT BY HAND. Re-run `make gen` after changing the descriptor.
//
// The mechanical wasm loader: typed exports + the fixed marshalling seam.
// Per-brick codec/semantics live in the (still hand-written) *_bridge.ts.

import { wasmBytes } from "./embedded.generated.ts";

interface SyncExports {
  memory: WebAssembly.Memory;
  luv_alloc(len: number): number;
  luv_free(ptr: number, len: number): void;
  luv_build_request(i: number, l: number, a: number, b: number): number;
  luv_parse_reply(i: number, l: number, a: number, b: number): number;
  luv_build_anthropic_request(i: number, l: number, a: number, b: number): number;
  luv_parse_anthropic_reply(i: number, l: number, a: number, b: number): number;
  luv_validate_tool_args(i: number, l: number, a: number, b: number): number;
  luv_classify_error(i: number, l: number, a: number, b: number): number;
  luv_extract_object(i: number, l: number, a: number, b: number): number;
  luv_pending_tool_calls(i: number, l: number, a: number, b: number): number;
  luv_respond_tool_call(i: number, l: number, a: number, b: number): number;
  luv_decoder_new(): number;
  luv_decoder_free(handle: number): void;
  luv_decoder_feed(h: number, i: number, l: number, a: number, b: number): number;
  agent_start(i: number, l: number): number;
  agent_poll(h: number, a: number, b: number): number;
  agent_feed_reply(h: number, i: number, l: number): number;
  agent_feed_tools(h: number, i: number, l: number): number;
  agent_abort(h: number): void;
  agent_destroy(h: number): void;
  // Generic lookup for the per-brick (i,l,a,b)->i32 exports.
  [name: string]: unknown;
}

// Synchronous instantiation at module load (no top-level await). Safari/
// Firefox/Node/Bun have no size cap; Chrome raised its main-thread limit
// to 8 MB in Chrome 115 (our wasm ~116 KB) — effective floor Chrome 115.
const instance = new WebAssembly.Instance(
  new WebAssembly.Module(wasmBytes),
  {},
);
const ex = instance.exports as unknown as SyncExports;

const u8 = (): Uint8Array => new Uint8Array(ex.memory.buffer);
const dv = (): DataView => new DataView(ex.memory.buffer);

function invoke(
  fn: (i: number, l: number, a: number, b: number) => number,
  input: Uint8Array,
  what: string,
): Uint8Array {
  let inPtr = 0;
  if (input.length > 0) {
    inPtr = ex.luv_alloc(input.length);
    if (inPtr === 0) throw new Error("luv_alloc failed");
    u8().set(input, inPtr);
  }
  const cell = ex.luv_alloc(8);
  try {
    const status = fn(inPtr, input.length, cell, cell + 4);
    if (status !== 0) throw new Error(`${what} failed: status ${status}`);
    const outPtr = dv().getUint32(cell, true);
    const outLen = dv().getUint32(cell + 4, true);
    const out = u8().slice(outPtr, outPtr + outLen);
    ex.luv_free(outPtr, outLen);
    return out;
  } finally {
    if (input.length > 0) ex.luv_free(inPtr, input.length);
    ex.luv_free(cell, 8);
  }
}

/** Generic synchronous call to an (in,in_len,out_ptr,out_len)->i32 export.
 *  The shared low-level seam every per-brick bridge uses — bricks own
 *  their codec, not this file. */
export function callWasm(exportName: string, input: Uint8Array): Uint8Array {
  const fn = ex[exportName] as
    | ((i: number, l: number, a: number, b: number) => number)
    | undefined;
  if (typeof fn !== "function") {
    throw new Error(`wasm export not found: ${exportName}`);
  }
  return invoke((i, l, a, b) => fn(i, l, a, b), input, exportName);
}

// Streaming SSE decoder — stateful handle (sse_decoder brick).
export function decoderNew(): number {
  const h = ex.luv_decoder_new();
  if (h === 0) throw new Error("luv_decoder_new failed");
  return h;
}

export function decoderFree(handle: number): void {
  ex.luv_decoder_free(handle);
}

export function decoderFeed(handle: number, chunk: Uint8Array): Uint8Array {
  let inPtr = 0;
  if (chunk.length > 0) {
    inPtr = ex.luv_alloc(chunk.length);
    if (inPtr === 0) throw new Error("luv_alloc failed");
    u8().set(chunk, inPtr);
  }
  const cell = ex.luv_alloc(8);
  try {
    const st = ex.luv_decoder_feed(handle, inPtr, chunk.length, cell, cell + 4);
    if (st !== 0) throw new Error(`luv_decoder_feed failed: status ${st}`);
    const op = dv().getUint32(cell, true);
    const ol = dv().getUint32(cell + 4, true);
    const out = u8().slice(op, op + ol);
    ex.luv_free(op, ol);
    return out;
  } finally {
    if (chunk.length > 0) ex.luv_free(inPtr, chunk.length);
    ex.luv_free(cell, 8);
  }
}

// Sans-IO agent loop — handle-based (the agent host driver).
export function agentStart(input: Uint8Array): number {
  let inPtr = 0;
  if (input.length > 0) {
    inPtr = ex.luv_alloc(input.length);
    if (inPtr === 0) throw new Error("luv_alloc failed");
    u8().set(input, inPtr);
  }
  try {
    const h = ex.agent_start(inPtr, input.length);
    if (h === 0) throw new Error("agent_start failed");
    return h;
  } finally {
    if (input.length > 0) ex.luv_free(inPtr, input.length);
  }
}

/** poll -> the tag+payload frame (caller parses tag byte 0). */
export function agentPoll(handle: number): Uint8Array {
  const cell = ex.luv_alloc(8);
  try {
    const st = ex.agent_poll(handle, cell, cell + 4);
    if (st !== 0) throw new Error(`agent_poll failed: status ${st}`);
    const op = dv().getUint32(cell, true);
    const ol = dv().getUint32(cell + 4, true);
    const out = u8().slice(op, op + ol);
    ex.luv_free(op, ol);
    return out;
  } finally {
    ex.luv_free(cell, 8);
  }
}

function agentFeed(
  fn: (h: number, i: number, l: number) => number,
  handle: number,
  bytes: Uint8Array,
  what: string,
): void {
  let p = 0;
  if (bytes.length > 0) {
    p = ex.luv_alloc(bytes.length);
    if (p === 0) throw new Error("luv_alloc failed");
    u8().set(bytes, p);
  }
  try {
    const st = fn(handle, p, bytes.length);
    if (st !== 0) throw new Error(`${what} failed: status ${st}`);
  } finally {
    if (bytes.length > 0) ex.luv_free(p, bytes.length);
  }
}

export function agentFeedReply(handle: number, bytes: Uint8Array): void {
  agentFeed((h, i, l) => ex.agent_feed_reply(h, i, l), handle, bytes, "agent_feed_reply");
}
export function agentFeedTools(handle: number, bytes: Uint8Array): void {
  agentFeed((h, i, l) => ex.agent_feed_tools(h, i, l), handle, bytes, "agent_feed_tools");
}
export function agentAbort(handle: number): void {
  ex.agent_abort(handle);
}
export function agentDestroy(handle: number): void {
  ex.agent_destroy(handle);
}
