// @generated by core/tools/gen_wire.zig from core/src/wasm_abi/wire.zig — DO NOT EDIT BY HAND.
// One declarative schema drives this TS framing codec AND the
// schema-driven Zig encoder. Re-run `make gen` after editing wire.zig.

export function encodeToolArgsIn(args: Uint8Array, schema: Uint8Array | undefined): Uint8Array {
  const has = schema !== undefined;
  const total = 0 + 4 + args.length + 1 + (has ? 4 + schema!.length : 0);
  const buf = new Uint8Array(total);
  const dv = new DataView(buf.buffer);
  let pos = 0;
  dv.setUint32(pos, args.length, true); pos += 4;
  buf.set(args, pos); pos += args.length;
  buf[pos] = has ? 1 : 0; pos += 1;
  if (has) {
    dv.setUint32(pos, schema!.length, true); pos += 4;
    buf.set(schema!, pos); pos += schema!.length;
  }
  return buf;
}
