// @generated by core/tools/gen_ts_types.zig from
// core/src/morphisms/luv/luv.zig — DO NOT EDIT BY HAND.
//
// Source of truth for the canonical pure-data type shapes. Re-run
// `make gen-ts` after changing luv.zig. types.ts re-exports the
// structurally-identical subset (Role, StopReason, Usage); the rest
// are the canonical reference projection.

export type Role = "system" | "user" | "assistant";

export type StopReason = "end_turn" | "max_tokens" | "content_filter" | "stop_sequence" | "tool_use" | "other";

export type ToolResult = { readonly ok: string } | { readonly err: string };

export interface ToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: unknown;
  readonly result?: ToolResult;
}

export interface Tool {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: unknown;
}

export interface Message {
  readonly role: Role;
  readonly text: string;
  readonly toolCalls: ToolCall[];
}

export type Conversation = Message[];

export interface Usage {
  readonly promptTokens: number;
  readonly completionTokens: number;
  readonly totalTokens: number;
}

export interface Reply {
  readonly message: Message;
  readonly stopReason: StopReason;
  readonly usage?: Usage;
}

